swagger: '2.0'
info:
  description: |
    Initial version for server centric API
  version: "1.0.0"
  title: umanexus - Heatmap
  contact:
    email: pafmon@gmail.com
host: "umanexus.herokuapp.com"
basePath: "/api/v1"
paths:
  /locations:
    x-swagger-router-controller : "Default"
    post:
      summary: Register a Location in the server
      operationId: registerLocation
      responses:
        '405':
          description: Invalid Location object
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Location to be registered
        required: true
        schema:
          type: object
          properties:
            latitude:
              description: "Location latitude"
              example    : 37.39253 
              type       : number
            longitude:
              description: "Location longitude"
              example    : -5.99407
              type       : number
            timestamp:
              type: string
              format: date-time
            
  /heatmaps:
    x-swagger-router-controller : "Default"
    get:
      summary: Obtain a heatmap
      operationId: buildHeatMap
      produces:
      - application/json
      parameters:
        - name: period.from
          in: query
          description: "Relative Time stamp (in RFC3339 / ISO 8601 format), e.g. '2017-11-02T12:00:00'"
          required: true
          type: string
          format: date-time
        - name: period.to
          in: query
          description: "Relative Time stamp (in RFC3339 / ISO 8601 format), e.g. '2017-11-02T14:00:00'"
          required: true
          type: string
          format: date-time
        - name: area.center.latitude
          in: query
          description: "Area center latitude (with 5 digits precision), e.g. '37.39253'"
          required: true
          type       : number
        - name: area.center.longitude
          in: query
          description: "Area center latitude (with 5 digits precision), e.g. '-5.99407'"
          required: true
          type       : number
        - name: area.radius
          in: query
          description: "Area radius in meters (max 10 km), e.g. '1000'"
          required: true
          type       : integer
          minimum   : 1
          maximum   : 10000
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              type: object
              properties:
                latitude:
                  description: "Location latitude (with 5 digits precision)"
                  example    : 37.39253 
                  type       : number
                longitude:
                  description: "Location longitude (with 5 digits precision)"
                  example    : -5.99407
                  type       : number
                intensity:
                  type: integer
